### ISSUE TITLE
Missing Images for Glock-18 | Gamma Doppler & Talon | Dopplers

### ISSUE THREAD

**Issue by antal-k** [Step7750/node-csgo-cdn#45]
For some reason, it's returning undefined for these items.

Talon Knife missing Phase images, gems are fine.

`cdn.getItemNameURL(marketHashName, phase)`

**Comment by wavpro** [comment]
After doing some research on this issue, it seems to affect not only glock and talon dopplers, it also affects the Shadow Dagger Doppler and Butterfly Doppler on phase 2, sapphire and black pearl.

Due to inactivity of this project and my need to get a working version of the package, I've created a [fork](https://www.npmjs.com/package/cs2-cdn) of this project, and fixed this, the 404 issue and more. It's not 1:1 compatible, but it adds things like typescript support.
