### ISSUE TITLE
Still some missing Items 

### ISSUE THREAD

**Issue by jayjo29** [Step7750/node-csgo-cdn#5]
[missing_items.txt](https://github.com/Step7750/node-csgo-cdn/files/1642294/missing_items.txt)

Thanks for your really fast reply :- )

now the item I told you is existing.
But unfortunately there are still alot of missing Items, I'm not sure if I did something wrong or they are not correctly written by myself.
Please look at the .txt file, this are the items, which are listed as undefined.

Thanks again in advance for your help :-)

**Comment by Step7750** [comment]
For the weapons, it looks like there are collisions in the skin names. For example, the "Black Laminate" skin has the two corresponding English tags `PaintKit_hy_ak47lam_bw_Tag` and `Paintkit_cu_stonewash_Tag`.

From a glance, unless we want to parse the highly subject to change comments in csgo_english, we can iterate and check through possibilities as we find them in the file. Therefore, we can check all matches for the "Black Laminate" tag in csgo_english and cross it with items_game_cdn.

**Comment by Step7750** [comment]
Some of the items in your list have the incorrect name.

`(Holo-Foil)` should be `(Holo/Foil)`

**Comment by Step7750** [comment]
There is a very peculiar thing with `ESL Cologne 2014 Challengers`. There are no references to it in the language file, and when you go to the [Steam Market](http://steamcommunity.com/market/listings/730/ESL%20Cologne%202014%20Challengers) page, it shows the `ESL One Cologne 2014 Legends` page.

The same is true for `ESL Cologne 2014 Legends` which redirects to `ESL One Cologne 2014 Challengers`.

These two items, since they are not contained within the language files, most likely cannot exist within the game either, so they aren't supported.

**Comment by Step7750** [comment]
Thanks for the list, I've fixed all of them :)

You can update to v1.1.0 for the changes.

**Comment by jayjo29** [comment]
Thanks very very much stepan!
Everthing's working smoothly now!
Wish you the best for your upcoming degree ;-)

Am 20.01.2018 03:26 schrieb "Stepan Fedorko-Bartos" <
notifications@github.com>:
